package io.github.MoYuSOwO.farmersDelightRepaper.block;

public enum Blocks {
    CUTTING_BOARD,
    COOKING_POT,
    ONIONS_STAGE_0,
    ONIONS_STAGE_1,
    ONIONS_STAGE_2,
    ONIONS_STAGE_3,
    TOMATOES_STAGE_0,
    TOMATOES_STAGE_1,
    TOMATOES_STAGE_2,
    TOMATOES_STAGE_3,
    TOMATOES_STAGE_4,
    TOMATOES_STAGE_5,
    TOMATOES_STAGE_6,
    TOMATOES_STAGE_7,
    CABBAGES_STAGE_0,
    CABBAGES_STAGE_1,
    CABBAGES_STAGE_2,
    CABBAGES_STAGE_3,
    CABBAGES_STAGE_4,
    CABBAGES_STAGE_5,
    CABBAGES_STAGE_6,
    CABBAGES_STAGE_7
}
